title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-hacker

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 6052
google_analytics: G-Z7Y45BF3RZ