title: "0xff"
iconURL: assets/default-icon.png
theme: jekyll-theme-hacker

# for a clean URL
permalink: :slug

social:
  twitter: 
  github: Ydvmtzv

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 6052
google_analytics: G-KNBW4LC5XM